baseURL = "https://louisandrada.com/"
languageCode = "en-us"
title = "Louis Andrada"
theme = "portfolio-theme"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[permalinks]
artworks = "/artworks/:filename/"
archive = "archive/:filename/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
